### ISSUE TITLE
appearing camera

### ISSUE THREAD

**Issue by vdsprakash** [sbhklr/QRCoder#9]
HI @sbhklr,
while implementing this pod successfully working in simulator but displaying camera in device.As I expected is show the Generated qrCode not Camera to scan @sbhklr in simulater showing directly the qrCode screen that was perfect but while running in the device camera screen without capturing button appearing 
![img_0005](https://user-images.githubusercontent.com/23026717/47895219-307c2f00-de8d-11e8-879a-46f781cfbcd8.png)
![simulator screen shot - iphone 6s - 2018-11-02 at 10 48 44](https://user-images.githubusercontent.com/23026717/47895220-307c2f00-de8d-11e8-9111-7bf5d501c1d2.png)

**Comment by sebromero** [comment]
Hi @vdsprakash. 
Please be clear about what your problem is: What was the expected outcome, what happened instead? Provide details about how someone else can recreate the problem.
In most cases people who publish their code to Github work on these projects in their free time. To ask them to do something ASAP isn't good etiquette and will probably lead to the opposite.
